# Generated by Django 4.2.5 on 2023-09-30 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golocalapp', '0002_postimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='transportation',
        ),
        migrations.AddField(
            model_name='post',
            name='transportation',
            field=models.ManyToManyField(blank=True, to='golocalapp.transportation'),
        ),
    ]
