# Generated by Django 4.2.5 on 2023-09-30 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golocalapp', '0003_remove_post_transportation_post_transportation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='transportation',
        ),
        migrations.DeleteModel(
            name='Transportation',
        ),
        migrations.AddField(
            model_name='post',
            name='transportation',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
