# Generated by Django 4.1.7 on 2023-09-30 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golocalapp', '0004_remove_post_transportation_delete_transportation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='lodging',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='restaurant',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='trek',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='difficulty',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
