# Generated by Django 4.1.7 on 2023-09-30 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('golocalapp', '0006_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
