# Generated by Django 4.2.5 on 2023-09-30 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('golocalapp', '0007_alter_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
