# Generated by Django 4.2.5 on 2023-10-01 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golocalapp', '0008_remove_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
