# Generated by Django 4.1.7 on 2023-10-01 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('golocalapp', '0007_remove_post_likes'),
        ('golocalapp', '0009_post_likes'),
        ('golocalapp', '0010_alter_post_image'),
    ]

    operations = [
    ]
