# Generated by Django 4.1.7 on 2023-10-01 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golocalapp', '0011_merge_20231001_0420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='post_images/'),
        ),
    ]
