# Generated by Django 4.2.5 on 2023-10-21 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('golocalapp', '0015_alter_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='name',
            new_name='location_name',
        ),
    ]
