# Generated by Django 4.2.5 on 2023-10-21 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golocalapp', '0016_rename_name_post_location_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='location_name',
        ),
        migrations.AddField(
            model_name='post',
            name='coordinates',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='location',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
