# Generated by Django 4.2.5 on 2023-10-22 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golocalapp', '0017_remove_post_location_name_post_coordinates_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='lodging',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='restaurant',
            field=models.BooleanField(default=False),
        ),
    ]
